server:
  port: 8189
  servlet:
    context-path: /cafefresh

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: cafefresh
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 12345
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  docker:
    compose:
      file: compose.yml
      enabled: true
#      username: ${REDISUSER}
#      url: ${REDIS_URL}

#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate=DEBUG;StatementCreatorUtils=TRACE
utils:
  cart:
    prefix: CAFE_FRESH_CART_